-- Seed Data for Library Management System
-- This file contains sample data for testing

-- Note: Password is 'admin123' hashed with bcrypt (you'll need to run this after backend is set up)
-- For now, we'll use a placeholder. The actual hash will be generated by the backend.

-- Insert Admin User
-- Password: admin123 (will be hashed by backend)
INSERT INTO users (name, email, password, role) VALUES
('Admin User', 'admin@library.com', '$2a$10$ygJfqR3MSw/DCWK8CnLwyedW77o9eFd9RqORXwQvE3cbucbC9NkPa', 'ADMIN');

-- Insert Sample Student Users
INSERT INTO users (name, email, password, role) VALUES
('John Doe', 'john@student.com', '$2a$10$luh3Wtp53gGddnSmUbgK..1uUVAP76d5RZJvsW26rPWxJnz9VvtHG', 'STUDENT'),
('Jane Smith', 'jane@student.com', '$2a$10$luh3Wtp53gGddnSmUbgK..1uUVAP76d5RZJvsW26rPWxJnz9VvtHG', 'STUDENT'),
('Bob Johnson', 'bob@student.com', '$2a$10$luh3Wtp53gGddnSmUbgK..1uUVAP76d5RZJvsW26rPWxJnz9VvtHG', 'STUDENT');

-- Insert Sample Books
INSERT INTO books (title, authorid, author, isbn, category, quantity, available_quantity) VALUES
('The Great Gatsby', 1, 'F. Scott Fitzgerald', '978-0743273565', 'Fiction', 5, 5),
('To Kill a Mockingbird', 2, 'Harper Lee', '978-0061120084', 'Fiction', 3, 3),
('1984', 3, 'George Orwell', '978-0451524935', 'Fiction', 4, 4),
('Pride and Prejudice', 4, 'Jane Austen', '978-0141439518', 'Romance', 2, 2),
('The Catcher in the Rye', 5, 'J.D. Salinger', '978-0316769174', 'Fiction', 3, 3),
('Harry Potter and the Sorcerer''s Stone', 6, 'J.K. Rowling', '978-0590353427', 'Fantasy', 6, 6),
('The Hobbit', 7, 'J.R.R. Tolkien', '978-0547928227', 'Fantasy', 4, 4),
('Introduction to Algorithms', 8, 'Thomas H. Cormen', '978-0262033848', 'Computer Science', 3, 3),
('Clean Code', 9, 'Robert C. Martin', '978-0132350884', 'Computer Science', 5, 5),
('Design Patterns', 10, 'Erich Gamma', '978-0201633610', 'Computer Science', 2, 2),
('The Pragmatic Programmer', 11, 'Andrew Hunt', '978-0135957059', 'Computer Science', 4, 4),
('Sapiens', 12, 'Yuval Noah Harari', '978-0062316097', 'History', 3, 3),
('Educated', 13, 'Tara Westover', '978-0399590504', 'Biography', 2, 2),
('Becoming', 14, 'Michelle Obama', '978-1524763138', 'Biography', 3, 3),
('The Lean Startup', 15, 'Eric Ries', '978-0307887894', 'Business', 4, 4);

-- Insert Sample Transactions (some issued, some returned)
INSERT INTO transactions (user_id, book_id, issue_date, due_date, return_date, status) VALUES
(2, 1, '2026-02-01', '2026-02-15', '2026-02-14', 'RETURNED'),
(2, 8, '2026-02-10', '2026-02-24', NULL, 'ISSUED'),
(3, 6, '2026-02-05', '2026-02-19', '2026-02-18', 'RETURNED'),
(3, 9, '2026-02-12', '2026-02-26', NULL, 'ISSUED'),
(4, 3, '2026-02-08', '2026-02-22', NULL, 'ISSUED');

-- Update available quantities based on issued books
UPDATE books SET available_quantity = available_quantity - 1 WHERE id IN (8, 9, 3);

-- Display success message
SELECT 'Seed data inserted successfully!' AS message;
SELECT COUNT(*) AS total_users FROM users;
SELECT COUNT(*) AS total_books FROM books;
SELECT COUNT(*) AS total_transactions FROM transactions;
